### PR TITLE
Draft: Refactoring of selection method of packages incl time and well selection

### PR DESCRIPTION
**Pull request by Manangka**
In GitLab by @jdelsman on Jan 18, 2021, 09:22

Moved selection method down to packages, giving each package a selection method.
- Time selection: selects the active stress for a selected time. So if the t of the stress starts at say 2000-01-01, and you select slice(2000-01-05, 2000-02-01), this time is included (and its time renamed to 2000-01-05)
- Well handling: the different nature of the Well package necessitates a different handling of the sel method. It now allows for selection on the underlying dataframe. Also allow for time selection. The active time is selected per separate well.

TODO: 
- [x] documentation in docstring of package, especially time foo
- [ ] more user guide documentation...

### CODE REVIEW

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 18, 2021, 12:05

marked this merge request as **draft**

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 18, 2021, 14:22

added 2 commits

<ul><li>44def25f - docstrings</li><li>86e81fba - black</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=136742714&start_sha=b4925ba7092f67b8e651b69c9c02be20b0da8377)

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 17:35

added 1 commit

<ul><li>7933cb30 - Some docstring formatting changes:</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=136804502&start_sha=8c54b4366059935695f18f68a028d1ef8d2826fe)

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 20:58

Commented on [imod/wq/pkgbase.py line 505](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..7933cb308f7dc8f614a95e8e1f359b5e51224d40#diff-0fc7ca494e15b870e8e448a8c2583866R505)



Are there packages in which time is a dimension, but the package is not a BoundaryCondition?

I'm wondering if this check is necessary, since ``.pop()`` will give the appropriate None value.

I think ``time_sel`` might be called ``time_indexer``?
``sel_dims`` maybe ``indexers``?
Finally ``sel`` maybe ``selection``?

Would this work? This cleans up the logic a little:

```python
        indexers = {k: v for k, v in dimensions.items() if k in self.dims}
        time_indexer = indexer.pop("time", None)
        if len(indexers) == 0:
            return self 
        else:
            # Note: .sel for Well is overloaded
            # explicitly call xr.Dataset's sel method
            selection = xr.Dataset.sel(
                self, indexers, method=method, tolerance=tolerance, drop=drop
            )
            if time_indexer:
                selection = selection._sel_time(time_indexer)
            return selection
```


P.S.
I just found out that the "Pythonic" way of checking an empty dict is:
```python
if d:
    print("not empty")
```
But ``len(d)`` seems a lot clearer.

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 76](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL76)



I think the ``dimensions`` are my faulty choice, but maybe we ought to use the opportunity to get them in line with the xarray nomenclature?

https://xarray.pydata.org/en/stable/generated/xarray.DataArray.sel.html

If we're just forwarding everything, could we use the same keyword arguments?

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 851](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL851)



Assert statements are for debugging, these look like ValueErrors to me.

(Asserts will be ignored by running ``python -O``, where I think the O stands for "optimized")

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 871](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL871)



Is there a reason for putting this function in this scope?
It is only called once later on, with dims None.

I'm also having trouble telling what it does. Given the dropna, the goal is to get the extremities of the coordinate array once nodata values have been removed, and ``dtmp`` is the cellsize?

Is this function maybe useful?
https://gitlab.com/deltares/imod/imod-python/-/blob/master/imod/util.py#L303

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 900](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL900)



``ml`` might as well be ``model``?

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 901](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..444a081785563eef03a8419a69870b827749c887#diff-fabe22d7c91992d47c09b69e252171ffL901)



``pkgname`` instead of ``pck``?

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 902](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..444a081785563eef03a8419a69870b827749c887#diff-fabe22d7c91992d47c09b69e252171ffL902)



``variable`` instead of ``d``?

I think a few assignments would improve the readability, e.g.:

```python
da = model[pkgname][variable]
model[pkgname][variable] = da.where(is_edge)
```

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 905](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..444a081785563eef03a8419a69870b827749c887#diff-fabe22d7c91992d47c09b69e252171ffL905)



I'd go with:

```python
# Check if geospatial (IDF) data
if "x" in da.dims and "y" in da.dims:
```

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 915](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..444a081785563eef03a8419a69870b827749c887#diff-fabe22d7c91992d47c09b69e252171ffL915)



This is a very expensive way of shifting the array: combine_first does an element-wise check on every value.

Maybe:
```python
concentration_boundary = xr.concat(
    [
        concentration_boundary.shift(time=-1).isel(slice(None, -1)),
        concentration_boundary.isel(time=-1),
    ],
    dim="time",
)
```

(If I didn't mess up the direction of the shift)

isel also works directly, I think, but it'll duplicate the time coordinate, which has to be restored then:
```python
time = concentration_boundary["time"]
index = np.arange(1, time.size + 1)
index[-1] -= 1
concentration_boundary = concentration_boundary.isel(time=index)
concentration_boundary["time"] = time
```

First one is more readable I think.

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/model.py line 914](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..444a081785563eef03a8419a69870b827749c887#diff-fabe22d7c91992d47c09b69e252171ffL914)



Is already boolean, no need for == 1

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/pkgbase.py line 500](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..7933cb308f7dc8f614a95e8e1f359b5e51224d40#diff-0fc7ca494e15b870e8e448a8c2583866R500)



I don't think this is quite right: if it's a keyword in the docstring, it should be a keyword in the function args.
Forwarding the kwargs shouldn't be a problem at any rate as long as it's all consistent.

It also emphasizes that the dimensions aren't the right keyword, as I mentioned for ``model.py``, methinks.

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:11

Commented on [imod/wq/timeutil.py line 43](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..444a081785563eef03a8419a69870b827749c887#diff-998059be0f2df142fb67c1c48653539eR43)



Nice

**Comment by Manangka** [comment]
In GitLab by @Huite on Jan 18, 2021, 21:19

I haven't gotten to the Well changes yet, I'll have another look tomorrow.

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 10:09

Commented on [imod/wq/pkgbase.py line 505](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..7933cb308f7dc8f614a95e8e1f359b5e51224d40#diff-0fc7ca494e15b870e8e448a8c2583866R505)



@time in non-BoundaryCondition packages: it is not uncommon to have a time coordinate dangling around in your dataset, even it is not a BC. I didn't want it to fail on that. So the check is for trying to access sel_time if not a BC. But this would be handled by the in dims check. So yeah, would work I think.

@the renaming in accordance with xarray: yeah, I would prefer that. The dimensions was indeed already there.

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 10:35

@ extent and binary dilation: as it is now: the extent da has the size of the original model. So binary dilation is no problem, if it crosses the model bounds, there are no boundary conditions. And erosion gives a slightly smaller model than requested.

@ dimensions: indeed, move to xarray nomenclature.

@ get_clip_na_slices: will look into it. Goal is indeed to get smaller da's...

@ combine_first: sounds good

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 11:47

Commented on [imod/wq/model.py line 76](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL76)



as above, definitely in favor.

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 13:48

Commented on [imod/wq/pkgbase.py line 505](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..7933cb308f7dc8f614a95e8e1f359b5e51224d40#diff-0fc7ca494e15b870e8e448a8c2583866R505)



changed this line in [version 5 of the diff](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137005268&start_sha=7933cb308f7dc8f614a95e8e1f359b5e51224d40#39305054ddf7a53720fa10d402bb2e7cd53c8602_505_513)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 13:48

Commented on [imod/wq/pkgbase.py line 500](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..7933cb308f7dc8f614a95e8e1f359b5e51224d40#diff-0fc7ca494e15b870e8e448a8c2583866R500)



changed this line in [version 5 of the diff](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137005268&start_sha=7933cb308f7dc8f614a95e8e1f359b5e51224d40#39305054ddf7a53720fa10d402bb2e7cd53c8602_500_513)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 13:48

Commented on [imod/wq/pkgbase.py line 783](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..7933cb308f7dc8f614a95e8e1f359b5e51224d40#diff-0fc7ca494e15b870e8e448a8c2583866R783)



changed this line in [version 5 of the diff](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137005268&start_sha=7933cb308f7dc8f614a95e8e1f359b5e51224d40#39305054ddf7a53720fa10d402bb2e7cd53c8602_783_792)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 13:48

added 1 commit

<ul><li>b79bde93 - refactor pkgbase</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137005268&start_sha=7933cb308f7dc8f614a95e8e1f359b5e51224d40)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 14:56

added 2 commits

<ul><li>480f72c8 - refactored well selection</li><li>444a0817 - refactored well selection</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137027666&start_sha=b79bde936a69ff4a6ae2b7bd5064df44a978363c)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 14:56

marked the checklist item **documentation in docstring of package, especially time foo** as completed

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 19, 2021, 17:14

added 1 commit

<ul><li>f705d650 - bugfix time_indexer wel</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137075347&start_sha=8a1ea1b40e5b6517f0e839e0645fdcac3f18ed24)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 22, 2021, 17:50

Commented on [imod/wq/model.py line 76](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL76)



changed this line in [version 10 of the diff](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137976358&start_sha=f705d650481bb0c613c63808147ee3b4ad252380#2066972df4ca0eb4501d6d3e6a7e528917e68796_76_93)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 22, 2021, 17:50

Commented on [imod/wq/model.py line 851](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL851)



changed this line in [version 10 of the diff](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137976358&start_sha=f705d650481bb0c613c63808147ee3b4ad252380#2066972df4ca0eb4501d6d3e6a7e528917e68796_860_973)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 22, 2021, 17:50

Commented on [imod/wq/model.py line 900](https://github.com/Deltares/imod-python/compare/b37f653602b7010c69e1051d97c3fdfd7b845a37..f705d650481bb0c613c63808147ee3b4ad252380#diff-fabe22d7c91992d47c09b69e252171ffL900)



changed this line in [version 10 of the diff](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137976358&start_sha=f705d650481bb0c613c63808147ee3b4ad252380#2066972df4ca0eb4501d6d3e6a7e528917e68796_909_999)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 22, 2021, 17:50

added 1 commit

<ul><li>0cbf67d0 - model review comments</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137976358&start_sha=f705d650481bb0c613c63808147ee3b4ad252380)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 22, 2021, 18:00

added 1 commit

<ul><li>6852a06b - scoping of tests</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=137978636&start_sha=0cbf67d0a2ce962557a5733338b614619dad5e51)

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Jan 25, 2021, 09:29

added 1 commit

<ul><li>ae6b2cf7 - black...</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=138202997&start_sha=238084188a50a69ccc70f609c1e6c5682097beea)

**Comment by Manangka** [comment]
In GitLab by @Huite on Feb 15, 2021, 22:18

added 5 commits

<ul><li>e80b51a7 - Remove now-irrelevant comment</li><li>63aeff9e - Remove deprecated TODO</li><li>8d6ea7ac - Merge branch &#39;sel_time&#39; of https://gitlab.com/deltares/imod/imod-python into sel_time</li><li>810d42ac - sparse dataset for selection rather than dataframe</li><li>6f564b91 - Implement Well .sel via sparse Datasets</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=144487464&start_sha=ae6b2cf7afe92da9c207d4889e415e0bd1c22bfd)

**Comment by Manangka** [comment]
In GitLab by @Huite on Feb 16, 2021, 13:44

I've been doing some reworking of the Well selection, by utilizing sparse datasets, the regular `_sel_time` method will work. There's a lot of other stuff that doesn't quite work nicely with the sparse datasets, so I've opted for a temporary conversion from and to. Initializing and storing the data primarily as a sparse dataset is definitely not attractive currently.

While I got all the tests for the wel package working, I moved on to getting the tests working for the model as well.
Unfortunately, the sparse dataset doesn't index as nicely (slices work fine, but `.sel(x=[1.0, 2.0, 3.0], y=[1.0, 2.0, 3.0]` doesn't work). It can still be done in two steps, but the more serious limitation is that this approach only works if the coordinates of the wells agrees exactly with the x-y midpoints coordinates of `like`.

This breaks the zone selection for the well package. I think the only good solution is forwarding a (polygon) geometry to the well package `.sel` instead, and using geopandas to select the wells that actually fall inside.
Anyway, yet another special case for wells (which makes sense, it being the only point-based data)...

**Comment by Manangka** [comment]
In GitLab by @jdelsman on Mar 30, 2021, 17:49

added 1 commit

<ul><li>2708364a - added sparse to dependencies</li></ul>

[Compare with previous version](/deltares/imod/imod-python/-/merge_requests/111/diffs?diff_id=164839711&start_sha=6f564b916cef9a7b8a98f5e6a09e83cb4974e778)

**Comment by JoerivanEngelen** [comment]
Closing because this branch has been stale for 2 years. Furthermore, new features will be implemented in the ``mf6`` module, adding features to the ``wq``  is thinning out the team's capacity.

**Pull request closed without merging**
